### ISSUE TITLE
how to set timezone ?

### ISSUE THREAD

**Issue by hoang** [voltrue2/node-datetime#3]
i'm in UTC +7 timezone. How can i get current datetime with this timezone ?

**Comment by voltrue2** [comment]
Hello

~~you may use `setOffsetInHours` to adjust to your timezone.~~

Or 

~~When you create an instance of `DateTime`, the instance object has a hidden property '_now'. 
This property is the instance of `Date` and you can use regular set methods of native `Date` to set timezone.~~

**Correction**

When you create a new `datetime` object, you can pass the native `Date` instance as follows:

```javascript
var datetime = require('node-datetime');
var today = new Date(Date.UTC(year, month, day, hour, minute, second));
// pass today to datetime
var dt = datetime.create(today, 'd/m/Y');
```

Cheers.

**Comment by KrishnaVadlamudi44** [comment]
Hello @voltrue2 ,

How can I set the datetime.create() to create date time in specified timezone? like CST for example.

I ask this because when I run this package on my local machine it is pulling the time from timezone I am in but when deployed to a cloud based server it is pulling GMT timezone. How can I fix this?

**Comment by voltrue2** [comment]
Hi there,
  

  
You can pass an instance of Date class to date time.create().
  
So what you could do is to set the time zone to the instance of your Date object before you pass it to date time.create()
  

  
Cheers
  

  
  

  
  
>
